project:
  type: book
  output-dir: docs

execute:
  freeze: auto
  cache: true

book:
  title: "BiocPy: Porting Bioconductor representations to Python"
  author: "[Jayaram Kancherla](mailto:jayaram.kancherla@gmail.com)"
  date: "1/23/2023"
  search: true
  repo-url: https://github.com/BiocPy/tutorial
  repo-actions: [issue]
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: chapters/granges/index.qmd
      chapters:
      - chapters/granges/initialize.qmd
      - chapters/granges/slice-ops.qmd
      - chapters/granges/intra-inter-range.qmd
    - chapters/summary.qmd
    - chapters/references.qmd

bibliography: chapters/references.bib

format:
  html:
    theme: journal
  pdf:
    keep-tex: true
    documentclass: scrreprt



