project:
  type: book
  output-dir: docs

execute:
  freeze: auto
  cache: true

book:
  title: "BiocPy: Enabling Bioconductor workflows in Python"
  author: "[Jayaram Kancherla](mailto:jayaram.kancherla@gmail.com)"
  contributor: "[Aaron Lun](mailto:infinite.monkeys.with.keys@gmail.com)"
  favicon: ./assets/short.png
  site-url: https://biocpy.github.io/tutorial
  date: "1/16/2024"
  search: true
  repo-url: https://github.com/BiocPy/tutorial
  repo-actions: [issue]
  # downloads: [pdf, epub]
  sharing: [twitter]
  twitter-card: true
  cover-image: ./assets/full.png
  page-footer:
    center: 
      - text: "(c) BiocPy core contributors"
        href: chapters/summary.qmd
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - part: chapters/representations/index.qmd
      chapters:
        - chapters/representations/atomics.qmd
        - chapters/representations/biocframe.qmd
        - chapters/representations/genomicranges.qmd
        - chapters/representations/delayedarrays.qmd
        - chapters/representations/filebackedarrays.qmd
    - part: chapters/experiments/index.qmd
      chapters:
        - chapters/experiments/summarized_expt.qmd
        - chapters/experiments/singlecell_expt.qmd
        - chapters/experiments/extending_se.qmd
        - chapters/experiments/multiassay_expt.qmd
    - chapters/interop.qmd
    - chapters/workflow.qmd
    - part: chapters/extras/index.qmd
      chapters:
        - chapters/extras/iranges.qmd
    - chapters/philosophy.qmd
    - chapters/summary.qmd
    - chapters/sessioninfo.qmd
    # - chapters/references.qmd


bibliography: chapters/references.bib

format:
  html:
    theme: cosmo
    number-sections: false
    code-link: true
  # pdf:
  #   keep-tex: true
  #   documentclass: scrreprt
