project:
  type: book
  output-dir: docs

execute:
  freeze: auto
  cache: true

book:
  title: "BiocPy: Enabling Bioconductor workflows in Python"
  author: "[Jayaram Kancherla](mailto:jayaram.kancherla@gmail.com)"
  date: "1/4/2024"
  search: true
  repo-url: https://github.com/BiocPy/tutorial
  repo-actions: [issue]
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - chapters/philosophy.qmd
    - part: chapters/representations/index.qmd
      chapters:
        - chapters/representations/biocframe.qmd
        - chapters/representations/genomicranges.qmd
    - part: chapters/experiments/index.qmd
      chapters:
        - chapters/experiments/summarized_expt.qmd
        - chapters/experiments/singlecell_expt.qmd
        - chapters/experiments/extending_se.qmd
        - chapters/experiments/multiassay_expt.qmd
    - part: chapters/extras/index.qmd
      chapters:
        - chapters/extras/iranges.qmd
    - chapters/summary.qmd
    - chapters/sessioninfo.qmd
    - chapters/references.qmd


bibliography: chapters/references.bib

format:
  html:
    theme: journal
    number-sections: false
  pdf:
    keep-tex: true
    documentclass: scrreprt
