on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'devel'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages: |
            any::BiocManager
            any::alabaster
            any::scRNAseq
            any::rmarkdown
            any::knitr
            any::reticulate
      # - run: Rscript r_requirements.r

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Publish to GH Pages
        if: github.ref == 'refs/heads/master'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages # The branch the action should deploy to.
          render: false